# Generated by Django 5.2.3 on 2025-06-28 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شركة', 'verbose_name_plural': '1. الشركات'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'ملف شركة', 'verbose_name_plural': '2. ملفات الشركات'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراك', 'verbose_name_plural': '3. الاشتراكات'},
        ),
        migrations.AlterModelOptions(
            name='systempage',
            options={'ordering': ['parent__id', 'id'], 'verbose_name': 'صفحة نظام', 'verbose_name_plural': '4. صفحات النظام'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': '5. المستخدمون'},
        ),
        migrations.AddField(
            model_name='systempage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.systempage', verbose_name='يتبع صفحة'),
        ),
        migrations.AddField(
            model_name='systempage',
            name='url_name',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='اسم الرابط (من urls.py)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='classification',
            field=models.CharField(blank=True, choices=[('factory', 'مصنع'), ('store', 'متجر'), ('company', 'شركة خدمات')], max_length=50, null=True, verbose_name='تصنيف الشركة'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='has_completed_profile',
            field=models.BooleanField(default=False, verbose_name='أكمل ملفه'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='language',
            field=models.CharField(default='ar', max_length=10, verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعّال'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='serial_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='السيريال نمبر'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='systempage',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='المجموعات المسموح لها بالوصول'),
        ),
        migrations.AlterField(
            model_name='systempage',
            name='category',
            field=models.CharField(default='General', max_length=100, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='systempage',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='أيقونة Lucide'),
        ),
        migrations.AlterField(
            model_name='systempage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الصفحة المعروض'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
