# Generated by Django 5.2.3 on 2025-06-27 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('classification', models.CharField(choices=[('factory', 'مصنع'), ('store', 'متجر'), ('company', 'شركة خدمات'), ('other', 'أخرى')], max_length=50, verbose_name='تصنيف الشركة')),
                ('country', models.CharField(max_length=100, verbose_name='الدولة')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'الإنجليزية')], default='ar', max_length=10, verbose_name='لغة النظام')),
                ('has_completed_profile', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف شركة',
                'verbose_name_plural': 'ملفات الشركات',
            },
        ),
    ]
