# Generated by Django 5.2.3 on 2025-07-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('Asset', 'أصل'), ('Liability', 'التزام'), ('Equity', 'حقوق ملكية'), ('Revenue', 'إيراد'), ('Expense', 'مصروف')], max_length=20, verbose_name='نوع الحساب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='accounts.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.chartofaccount', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب في الدليل',
                'verbose_name_plural': 'دليل الحسابات',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ القيد')),
                ('description', models.CharField(max_length=255, verbose_name='البيان/الوصف')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مدين (صدر له)')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='دائن (صدر منه)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.chartofaccount', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.journalentry', verbose_name='القيد الأصلي')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
            },
        ),
    ]
