# Generated by Django 5.2.3 on 2025-06-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_companyprofile_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systempage',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='system_pages', to='auth.group', verbose_name='المجموعات المسموح لها بالوصول'),
        ),
        migrations.CreateModel(
            name='IPRegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='عنوان IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التسجيل')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='الشركة المسجلة')),
            ],
            options={
                'verbose_name': 'سجل تسجيل IP',
                'verbose_name_plural': 'سجلات تسجيل IP',
            },
        ),
    ]
