# Generated by Django 5.2.3 on 2025-07-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chartofaccount_journalentry_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('General', 'عام'), ('Sarf', 'سند صرف'), ('Qabd', 'سند قبض'), ('Taswya', 'تسوية عهدة'), ('Ajel', 'آجل')], default='General', max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
