# Generated by Django 5.2.3 on 2025-07-04 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الخزنة/الحساب')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد الحالي')),
                ('box_type', models.CharField(choices=[('cash', 'نقدية'), ('bank', 'بنكية'), ('custody', 'عهدة')], default='cash', max_length=20, verbose_name='نوع الخزنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashboxes', to='accounts.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'خزنة',
                'verbose_name_plural': 'الخزن',
            },
        ),
        migrations.CreateModel(
            name='CashboxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', 'تحصيل/إيداع'), ('out', 'صرف/سحب')], max_length=10, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('category', models.CharField(choices=[('salary', 'راتب'), ('expense', 'مصروف'), ('supplier_payment', 'دفعة لمورد'), ('customer_payment', 'تحصيل من عميل'), ('custody_settlement', 'تسوية عهدة'), ('other', 'أخرى')], max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(verbose_name='البيان/الوصف')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.cashbox', verbose_name='الخزنة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_transactions', to='accounts.company')),
            ],
            options={
                'verbose_name': 'حركة خزنة',
                'verbose_name_plural': 'حركات الخزن',
                'ordering': ['-date'],
            },
        ),
    ]
