# Generated by Django 5.2.3 on 2025-07-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_client_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, verbose_name='اسم الشغلانة / المشروع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الشغلانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_completed', models.BooleanField(default=False, verbose_name='هل اكتملت؟')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'شغلانة',
                'verbose_name_plural': 'الشغلانات',
            },
        ),
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='وصف بند التكلفة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.item', verbose_name='الصنف من المخزون')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='operations.job', verbose_name='الشغلانة')),
            ],
            options={
                'verbose_name': 'تكلفة شغلانة',
                'verbose_name_plural': 'تكاليف الشغلانات',
            },
        ),
    ]
