# Generated by Django 5.2.3 on 2025-07-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_client_supplier'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المادة')),
                ('category', models.CharField(choices=[('خشب', 'خشب'), ('اكسسوارات', 'اكسسوارات'), ('زجاج', 'زجاج'), ('تغليف', 'تغليف'), ('أخرى', 'أخرى')], max_length=100, verbose_name='فئة المادة')),
                ('unit_of_measure', models.CharField(max_length=50, verbose_name='وحدة القياس')),
                ('quantity_in_stock', models.FloatField(default=0.0, verbose_name='الكمية في المخزن')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الوحدة')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobcost',
            name='item',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المشروع')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='التكلفة الإجمالية')),
                ('status', models.CharField(choices=[('جديد', 'جديد'), ('قيد التنفيذ', 'قيد التنفيذ'), ('متوقف', 'متوقف'), ('تم التسليم', 'تم التسليم'), ('ملغي', 'ملغي')], default='جديد', max_length=50, verbose_name='حالة المشروع')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.client', verbose_name='العميل')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobCost',
        ),
    ]
