# Generated by Django 5.2.3 on 2025-07-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_material_remove_jobcost_job_remove_jobcost_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='البيان (نوع الخامة أو الخدمة)')),
                ('quantity', models.FloatField(default=1, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
            ],
            options={
                'verbose_name': 'بند تكلفة',
                'verbose_name_plural': 'بنود التكاليف',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='بيان الدفعة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم المتوقع'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='اسم الأوردر/المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('جديد', 'جديد'), ('قيد التنفيذ', 'قيد التنفيذ'), ('متوقف', 'متوقف'), ('بانتظار الدفع', 'بانتظار الدفع'), ('مكتمل', 'مكتمل'), ('ملغي', 'ملغي')], default='جديد', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='costitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='operations.project', verbose_name='المشروع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operations.project', verbose_name='المشروع'),
        ),
    ]
