# Generated by Django 5.2.3 on 2025-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_costitem_payment_delete_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم الأوردر/المشروع'),
            preserve_default=False,
        ),
    ]
