# Generated by Django 5.2.3 on 2025-07-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية'),
        ),
    ]
